name: public slides

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Set up npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        run: npm install -g @marp-team/marp-cli
      - name: basic test  
        run: 
          python3 md2html.py
      - name: Archive output figs 
        uses: actions/upload-artifact@v2
        with:
          name: test-output-figs
          path: test/test_fig
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: .